// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnCPJQ0Laafiuve23FDxQ48KX-8rdrGkE',
    appId: '1:146176156876:web:a5eddc7d9aade59c754e69',
    messagingSenderId: '146176156876',
    projectId: 'gdrive-40a7b',
    authDomain: 'gdrive-40a7b.firebaseapp.com',
    storageBucket: 'gdrive-40a7b.appspot.com',
    measurementId: 'G-MZJGNJN71V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAvB8wR7r6NKVxaqgwLYymSvLbmhw5l-k',
    appId: '1:146176156876:android:3817bdc395ab6bfa754e69',
    messagingSenderId: '146176156876',
    projectId: 'gdrive-40a7b',
    storageBucket: 'gdrive-40a7b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFjM2DbxPczxoovPGTF0XjFFkjzW4BqLU',
    appId: '1:146176156876:ios:d023aa35e857b12d754e69',
    messagingSenderId: '146176156876',
    projectId: 'gdrive-40a7b',
    storageBucket: 'gdrive-40a7b.appspot.com',
    iosBundleId: 'com.example.griveDart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFjM2DbxPczxoovPGTF0XjFFkjzW4BqLU',
    appId: '1:146176156876:ios:46b9523404f78539754e69',
    messagingSenderId: '146176156876',
    projectId: 'gdrive-40a7b',
    storageBucket: 'gdrive-40a7b.appspot.com',
    iosBundleId: 'com.example.griveDart.RunnerTests',
  );
}
